### ISSUE TITLE
The license in the nimble file says MIT, contrary to the Unlicense included in the repo

### ISSUE THREAD

**Issue by Zambito1** [CosmicToast/pipe#4]
https://github.com/CosmicToast/pipe/blob/e81c9d2613b0b8ec4b7238a44bb68b3656fa11ab/pipe.nimble#L6

I suppose this should match the license that is used.

**Comment by CosmicToast** [comment]
When I relicensed it, I didn't check pipe.nimble.
Thanks for letting me know!
Fixed in 70e0f6f (and tagged v0.1.1).
